In [1]:
2 == 2

True

In [2]:
2 == 1

False

In [3]:
'Hello' == 'bye'

False

In [4]:
'Bye' == 'bye'

False

In [6]:
'2' == 2

False

In [7]:
2.0 == 2

True

In [8]:
3 != 3

False

In [9]:
4 != 5

True

In [10]:
2 > 1

True

In [11]:
1 > 2

False

In [12]:
1 < 2

True

In [13]:
2 < 5

True

In [14]:
1 < 2 < 3

True

In [15]:
1 < 2 > 3

False

In [16]:
1 < 2 and 2 < 3

True

In [17]:
1 < 2 and 2 > 3

False

In [19]:
'h' == 'h' and (2 == 2)

True

In [20]:
100 == 1 or 2 == 2

True

In [21]:
100 == 1 or 2 == 20

False

In [22]:
not 1 == 1

False

In [1]:
400 > 5000

False

In [2]:
import numpy as np

In [3]:
x = np.array([[11,12,13],
           [14,15,16],
           [17,18,19]])

In [4]:
x[1:3,1:3]

array([[15, 16],
       [18, 19]])

In [5]:
score = np.array([12,20,3,13,5,18,13])

In [13]:
t =np.where(score < 10)
t

(array([2, 4]),)

In [11]:
score[np.where(score>10)]

array([12, 20, 13, 18, 13])

In [15]:
a = np.array([[3,30],
              [17,18],
              [5,19]])

In [16]:
a.shape

(3, 2)

In [17]:
a < 10

array([[ True, False],
       [False, False],
       [ True, False]])

In [21]:
t= np.where(a<10)
t

(array([0, 2]), array([0, 0]))

In [22]:
a[t]

array([3, 5])

In [28]:
np.take(score,[1,2])

array([20,  3])

In [29]:
np.take(score,[0,-1])

array([12, 13])

In [30]:
np.take(a,0)

np.int64(3)

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((2,3)) * 13

array([[13., 13., 13.],
       [13., 13., 13.]])

In [35]:
np.ones((4,5))*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [38]:
a = np.ones((5,5))
a[1:4,]=7
a

array([[1., 1., 1., 1., 1.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [1., 1., 1., 1., 1.]])

In [39]:
np . zeros(4)

array([0., 0., 0., 0.])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])